### ISSUE TITLE
BatchedGraphQLClient should handle errors properly

### ISSUE THREAD

**Issue by akoenig** [graphcool/http-link-dataloader#2]
While investigating https://github.com/graphcool/prisma/issues/1833 I figured that the client doesn't handle error responses properly.

It can be reproduced by:

  * Scaffold a new Prisma application (e.g. `typescript-advanced`) and deploy it to the local cluster
  * Define a different project name in `PRISMA_ENDPOINT` than the one that is configured in `database/prisma.yml`
  * Execute a mutation in the app layer

This leads to the following exception:

```sh
{ Error: results.filter is not a function
    at Object.checkResultAndHandleErrors (/Volumes/Data/projects/<my-namespace>/<my-project>/node_modules/graphql-binding/node_modules/graphql-tools/src/stitching/errors.ts:84:7)
    at Object.<anonymous> (/Volumes/Data/projects/<my-namespace>/<my-project>/node_modules/graphql-binding/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:97:14)
    at step (/Volumes/Data/projects/<my-namespace>/<my-project>/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:40:23)
    at Object.next (/Volumes/Data/projects/<my-namespace>/<my-project>/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:21:53)
    at fulfilled (/Volumes/Data/projects/<my-namespace>/<my-project>/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:12:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'results.filter is not a function',
  locations: [],
  path: [] }
```

When logging `response._raw` in https://github.com/graphcool/http-link-dataloader/blob/171aea40abc76f32acf34d683af61a3f6a619d99/src/BatchedGraphQLClient.ts#L45 before it gets to the `results.filter` you can see that the Prisma server answers with the actual error message, `results`, is therefore, `undefined` and `results.filter` fails.

**Comment by akoenig** [comment]
Short status report :) I tried to compile a PR for this problem, but having a hard time to throw the respective `ClientError` when the server does not return an array with response data, but something like `{code:3016, requestId:"api:api:cjddfw4fx000a0186k0mo15wb", error: "Project not found: 'core@dev'"}`. It is impossible to throw a `ClientError` when that comes down, because you're not able to identify the actual query that caused the problem.

The logic in those lines wouldn't work then: https://github.com/graphcool/http-link-dataloader/blob/a741e98cbf44756088762b441810e6860cf90d98/src/BatchedGraphQLClient.ts#L52-L62

**Comment by akoenig** [comment]
@timsuchanek Closing because of the fix: https://github.com/graphcool/http-link-dataloader/commit/325217908a6b799246b648f16c9170c2d4c5628a – Thanks a lot :)
